Num_list=[10,20,30,40,50,60,70,80,90]
print(Num_list)
print("Accessing the List Elements using Positive indexing")
print(Num_list[0])
print(Num_list[1])
print(Num_list[2])
print(Num_list[3])
print(Num_list[4])
print(Num_list[5])
print(Num_list[6])
print(Num_list[7])
print(Num_list[8])
print("Accessing the List Elements using negative indexing")
print(Num_list[-9])
print(Num_list[-8])
print(Num_list[-7])
print(Num_list[-6])
print(Num_list[-5])
print(Num_list[-4])
print(Num_list[-3])
print(Num_list[-2])
print(Num_list[-1])