'''
Write a python program to create a mobile class and perform instantiation for 10 objects
'''
class Mobile:
    def __init__(self):
        print("Mobile Class Constructor has been called...!")
M1=Mobile()
print(id(M1))
print(type(M1))
M2=Mobile()
print(id(M2))
print(type(M2))
M3=Mobile()
print(id(M3))
print(type(M3))
M4=Mobile()
print(id(M4))
print(type(M4))
M5=Mobile()
print(id(M5))
print(type(M5))
M6=Mobile()
print(id(M6))
print(type(M6))
M7=Mobile()
print(id(M7))
print(type(M7))
M8=Mobile()
print(id(M8))
print(type(M8))
M9=Mobile()
print(id(M9))
print(type(M9))
M10=Mobile()
print(id(M10))
print(type(M10))